bheemBoy/bheemBoy/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

bheemboy/urls.py
from django.conf.urls import include, url
from coursereg.admin import admin_site

urlpatterns = [
    url(r'^sudo/', admin_site.urls),
    url(r'', include('coursereg.urls'))
]

coursereg/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'coursereg'
urlpatterns = [
    url(r'^signin$', views.user.signin, name='signin'),
    url(r'^signout$', views.user.signout, name='signout'),
    url(r'^changepasswd$', views.user.change_passwd, name='change_passwd'),
    url(r'^forgotpasswd$', views.user.forgot_passwd, name='forgot_passwd'),
    url(r'^resetpasswd/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$', views.user.reset_passwd, name='reset_passwd'),

    url(r'^faq$', views.common.faq, name='faq'),
    url(r'^fatal$', views.common.fatal_error, name='fatal'),
    url(r'^profile$', views.common.profile, name='profile'),
    url(r'^$', views.common.index, name='index'),

    url(r'^participants/create$', views.participants.create, name='participants_create'),
    url(r'^participants/([0-9]+)/update$', views.participants.update, name='participants_update'),
    url(r'^participants/all/update$', views.participants.update_all, name='participants_update_all'),
    url(r'^participants/([0-9]+)/delete$', views.participants.delete, name='participants_delete'),

    url(r'^notifications/dismiss$', views.notifications.dismiss, name='notifications_dismiss'),
    url(r'^notifications/create$', views.notifications.notify, name='notify'),

    url(r'^instructor$', views.instructor.index, name='instructor'),
    url(r'^instructor/([0-9]+)$', views.instructor.detail, name='instructor_detail'),
    url(r'^instructor/new$', views.instructor.course_new, name='instructor_new_course'),
    url(r'^instructor/([0-9]+)/update$', views.instructor.course_update, name='instructor_update_course'),

    url(r'^adviser$', views.adviser.index, name='adviser'),
    url(r'^adviser/([0-9]+)$', views.adviser.detail, name='adviser_detail'),

    url(r'^dcc/report$', views.dcc.report, name='dcc_report'),
    url(r'^dcc/review$', views.dcc.review, name='dcc_review'),
    url(r'^dcc/([0-9]+)$', views.dcc.detail, name='dcc_detail'),
    url(r'^dcc/([0-9]+)/approve$', views.dcc.approve, name='dcc_approve'),
]

bheemboy/coursereg/views/student.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.utils import timezone
from datetime import timedelta
from coursereg import models
from django.contrib.auth import update_session_auth_hash

def index(request):
    if not request.user.adviser:
        messages.error(request, 'Adviser not assigned. Contact the administrator.')
        return redirect('coursereg:fatal')
    participants = [
        (
            p.course,
            p.state,
            p.grade,
            models.Participant.STATE_CHOICES[p.state][1],
            models.Participant.GRADE_CHOICES[p.grade][1],
            p.state == models.Participant.STATE_REQUESTED,
            p.id
        ) for p in models.Participant.objects.filter(user=request.user)]
    context = {
		'user_email': request.user.email,
        'user_id': request.user.id,
        'participants': participants,
        'courses': models.Course.objects.filter(last_reg_date__gte=timezone.now(),
                                                last_reg_date__lte=timezone.now()+timedelta(days=100)),
    }
    return render(request, 'coursereg/student.html', context)

@login_required
def faq(request):
	context = {
		'user_email': request.user.email,
	}
	return render(request, 'coursereg/student_faq.html', context)

@login_required
def profile(request):
    context = {
		'user_email': request.user.email,
        'user_full_name': request.user.full_name,
        'user_id': request.user.id,
        'adviser_full_name': request.user.adviser.full_name,
        'program': models.User.PROGRAM_CHOICES[request.user.program][1],
        'sr_no': request.user.sr_no,
    }
    return render(request, 'coursereg/student_profile.html', context)

@login_required
def participant_delete(request):
    assert request.method == 'POST'
    participant = models.Participant.objects.get(id=request.POST['participant_id'])
    assert participant.user_id == request.user.id
    if participant.state != models.Participant.STATE_REQUESTED:
        messages.error(request, 'Unable to unregister from the course. Please speak to the administrator.')
    else:
        participant.delete()
        messages.success(request, 'Unregistered from %s.' % participant.course)
    return redirect('coursereg:index')

@login_required
def participant_create(request):
    assert request.method == 'POST'
    course_id = request.POST['course_id']
    user_id = request.POST['user_id']
    assert int(user_id) == int(request.user.id)

    if not course_id:
        messages.error(request, 'Select the course you want to register for.')
    else:
        course = models.Course.objects.get(id=course_id)
        if models.Participant.objects.filter(user__id=user_id, course__id=course_id):
            messages.error(request, 'Already registered for %s.' % course)
        elif timezone.now().date() > course.last_reg_date:
            messages.error(request, 'Registration for %s is now closed.' % course)
        else:
            models.Participant.objects.create(
                user_id=user_id,
                course_id=course_id,
                participant_type=models.Participant.PARTICIPANT_CREDIT,
                state=models.Participant.STATE_REQUESTED,
                grade=models.Participant.GRADE_NA
            )
            messages.success(request, 'Successfully applied for %s.' % course)

    return redirect('coursereg:index')

coursereg/views/adviser.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.utils import timezone
from datetime import timedelta
from coursereg import models
from coursereg import utils
from django.core.exceptions import PermissionDenied
from django.conf import settings

@login_required
def index(request):
    if not request.user.user_type == models.User.USER_TYPE_FACULTY:
        raise PermissionDenied
    context = {
        'user_type': 'faculty',
        'nav_active': 'adviser',
        'user_email': request.user.email,
        'students': models.User.objects.filter(adviser=request.user).order_by('-is_active', '-date_joined')
    }
    return render(request, 'coursereg/adviser.html', context)

@login_required
def detail(request, student_id):
    student = models.User.objects.get(id=student_id)
    if not request.user == student.adviser:
        raise PermissionDenied
    is_last_reg_date_passed_for_all_courses = not any(not p.course.is_last_reg_date_passed() for p in models.Participant.objects.filter(user=student))
    if settings.WARN_REVIEW_BEFORE_LAST_DATE and not is_last_reg_date_passed_for_all_courses:
        messages.warning(request, 'Registration is still open. Visit this page after the last application date.')
    context = {
        'user_type': 'faculty',
        'nav_active': 'adviser',
        'user_email': request.user.email,
        'student': student,
        'reg_types': models.RegistrationType.objects.filter(is_active=True),
        'is_manual_faculty_review_enabled': settings.MANUAL_FACULTY_REVIEW,
        'can_adviser_add_courses_for_students': settings.CAN_ADVISER_ADD_COURSES_FOR_STUDENTS,
        'notifications': [(n.created_at, models.Notification.ORIGIN_CHOICES[n.origin][1], n.message)
            for n in models.Notification.objects.filter(user=student, is_adviser_acknowledged=False).order_by('-created_at')],
        'participants': list(models.Participant.objects.filter(user=student).order_by('-course__term__last_reg_date')),
        'is_adviser_review_needed': models.Participant.objects.filter(user=student, is_adviser_reviewed=False),
        'courses': models.Course.objects.filter(term__last_adviser_approval_date__gte=timezone.now(),
                                                term__start_reg_date__lte=timezone.now())
    }
    if not settings.MANUAL_FACULTY_REVIEW:
        models.Participant.objects.filter(user=student, is_adviser_reviewed=False).update(is_adviser_reviewed=True)
    return render(request, 'coursereg/adviser_detail.html', context)

coursereg/views/common.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from datetime import timedelta
from coursereg import models
from . import student, instructor, adviser, dcc
from django.contrib.auth import update_session_auth_hash

@login_required
def index(request):
    if request.user.is_superuser:
        return redirect('admin:index')
    elif request.user.user_type == models.User.USER_TYPE_STUDENT:
        return student.index(request)
    elif request.user.user_type == models.User.USER_TYPE_FACULTY:
        return redirect('coursereg:adviser')
    elif request.user.user_type == models.User.USER_TYPE_DCC:
        return redirect('coursereg:dcc_report')
    else:
        messages.error(request, "User type not recognized.")
        return redirect('coursereg:fatal')

def fatal_error(request):
    context = {}
    return render(request, 'coursereg/fatal.html', context)

@login_required
def faq(request):
    context = {
        'nav_active': 'faq',
        'user_email': request.user.email
    }
    if request.user.user_type == models.User.USER_TYPE_STUDENT:
        context['faqs'] = models.Faq.objects.filter(faq_for=models.Faq.FAQ_STUDENT)
        context['user_type'] = 'student'
    elif request.user.user_type == models.User.USER_TYPE_FACULTY:
        context['faqs'] = models.Faq.objects.filter(faq_for=models.Faq.FAQ_FACULTY)
        context['user_type'] = 'faculty'
    elif request.user.user_type == models.User.USER_TYPE_DCC:
        context['faqs'] = models.Faq.objects.filter(faq_for=models.Faq.FAQ_DCC)
        context['user_type'] = 'dcc'
    else:
        raise Http404('User type not recognized')

    return render(request, 'coursereg/faq.html', context)

@login_required
def profile(request):
    context = {
        'nav_active': 'profile',
        'user_email': request.user.email,
        'user_full_name': request.user.full_name,
        'department': request.user.department,
    }
    if request.user.user_type == models.User.USER_TYPE_STUDENT:
        context['user_type'] = 'student'
        context['adviser_full_name'] = request.user.adviser.full_name
        context['degree'] = request.user.degree
        context['sr_no'] = request.user.sr_no
    elif request.user.user_type == models.User.USER_TYPE_FACULTY:
        context['user_type'] = 'faculty'
    elif request.user.user_type == models.User.USER_TYPE_DCC:
        context['user_type'] = 'dcc'
    else:
        raise Http404('User type not recognized')

    return render(request, 'coursereg/profile.html', context)

coursereg/views/dcc.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from datetime import timedelta
from coursereg import models
from django.contrib.auth import update_session_auth_hash
from coursereg import utils
from django.db.models import Q, Count
from django.core.mail import send_mail
from django.core.exceptions import PermissionDenied
from django.views.decorators.http import require_POST
from coursereg import utils
from django.utils import timezone
from collections import defaultdict

@login_required
def report(request):
    if not request.user.user_type == models.User.USER_TYPE_DCC:
        raise PermissionDenied

    selected_term_ids = [int(i) for i in request.GET.getlist('term_ids')]

    participants_query = models.Participant.objects.filter(
        user__department=request.user.department,
        user__user_type=models.User.USER_TYPE_STUDENT,
        course__term__in=selected_term_ids
    )

    orderby = request.GET.get('orderby', 'degree')
    if orderby == 'course':
        participants = [p for p in participants_query.order_by('course', 'is_drop', '-registration_type', 'user__degree', 'user__full_name')]
    elif orderby == 'name':
        participants = [p for p in participants_query.order_by('user__full_name')]
    else:
        participants = [p for p in participants_query.order_by('user__degree', 'user__full_name')]

    context = {
        'user_type': 'dcc',
        'nav_active': 'report',
        'user_email': request.user.email,
        'dept': request.user.department,
        'orderby': orderby,
        'terms': models.Term.objects.filter(is_active=True).order_by('-last_reg_date'),
        'selected_term_ids': selected_term_ids,
        'participants': participants,
    }
    return render(request, 'coursereg/dcc_report.html', context)

@login_required
def review(request):
    if not request.user.user_type == models.User.USER_TYPE_DCC:
        raise PermissionDenied

    pending_advisers = set(p.user.adviser for p in models.Participant.objects.filter(user__department=request.user.department, participant_type=models.Participant.PARTICIPANT_STUDENT, is_adviser_reviewed=False))
    pending_instructors = set(instructor for p in models.Participant.objects.filter(user__department=request.user.department, participant_type=models.Participant.PARTICIPANT_STUDENT, is_instructor_reviewed=False) for instructor in p.course.instructors())
    pending_faculty = pending_advisers | pending_instructors

    active_students = defaultdict(list)
    oldest_recent_year = timezone.now().year - 1
    for student in models.User.objects.filter(user_type=models.User.USER_TYPE_STUDENT, is_active=True, department=request.user.department).order_by('-is_dcc_review_pending', '-date_joined','full_name'):
        regd = student.date_joined
        if regd.year >= oldest_recent_year:
            active_students['%s (Joined in %s %s)' % (student.degree, regd.strftime('%b'), regd.strftime('%Y'))].append(student)
        else:
            active_students['%s (Joined before %s)' % (student.degree, oldest_recent_year)].append(student)

    context = {
        'user_type': 'dcc',
        'nav_active': 'review',
        'user_email': request.user.email,
        'pending_faculty': pending_faculty,
        'pending_advisers': pending_advisers,
        'pending_instructors': pending_instructors,
        'degrees': models.Degree.objects.all().order_by('name'),
        'active_students': dict(active_students),
    }
    return render(request, 'coursereg/dcc_review.html', context)

@login_required
def detail(request, student_id):
    if not request.user.user_type == models.User.USER_TYPE_DCC:
        raise PermissionDenied
    student = models.User.objects.get(id=student_id)
    if not student or student.department != request.user.department:
        raise PermissionDenied

    context = {
        'user_type': 'dcc',
        'nav_active': 'review',
        'user_email': request.user.email,
        'student': student,
        'participants': models.Participant.objects.filter(user=student).order_by('-course__term__last_reg_date'),
        'notifications': [(n.created_at, models.Notification.ORIGIN_CHOICES[n.origin][1], n.message)
            for n in models.Notification.objects.filter(user=student, is_dcc_acknowledged=False).order_by('-created_at')],
    }
    return render(request, 'coursereg/dcc_detail.html', context)

@require_POST
@login_required
def approve(request, student_id):
    if not request.user.user_type == models.User.USER_TYPE_DCC:
        raise PermissionDenied
    student = models.User.objects.get(id=student_id)
    if not student or student.department != request.user.department:
        raise PermissionDenied
    student.is_dcc_review_pending = False
    student.is_dcc_sent_notification = False
    student.save()
    models.Notification.objects.filter(user=student).update(is_dcc_acknowledged=True)
    messages.success(request, 'Courses registered by %s approved.' % student.full_name)
    return redirect('coursereg:dcc_review')

coursereg/views/faculty.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.utils import timezone
from datetime import timedelta
from coursereg import models
from django.contrib.auth import update_session_auth_hash
import logging

@login_required
def index(request):
    pass

coursereg/templates/coursereg/adviser.html
{% extends "coursereg/base.html" %}

{% block body %}
{% include "coursereg/nav.html" %}
<div class="container" id="maincontainer">
    <div class="row top-buffer-1">
        <div class="col-md-12">
            <h1>Advisees</h1>
        </div>
    </div>
    {% if messages %}
    {% for message in messages %}
    <div class="row top-buffer-1">
        <div class="col-md-12">
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert alert-warning" role="alert">{{ message }}</div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {% endif %}
    <div class="row top-buffer-1">
        <div class="col-md-12">
            <table class="table table-striped">
            {% for student in students %}
                <tr>
                    <td>
                        {% if student.is_active %}
                        <a href="{% url 'coursereg:adviser_detail' student.id %}">{{ student.full_name }}</a>
                        {% if student.is_adviser_review_pending %}
                        <span class="label label-success">new</span>
                        {% endif %}
                        {% else %}
                        <a class="inactive" href="{% url 'coursereg:adviser_detail' student.id %}">{{ student.full_name }}</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

coursereg/templates/coursereg/course_update.html
{% extends "coursereg/base.html" %}

{% block body %}
{% include "coursereg/nav.html" %}
<div class="container" id="maincontainer">
    <div class="row top-buffer-1">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'coursereg:instructor' %}">Courses</a></li>
                <li class="breadcrumb-item"><a href="{% url 'coursereg:instructor_detail' course.id %}">{{ course }}</a></li>
                <li class="breadcrumb-item active">Edit</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h2>{{ course }}</h2>
            </div>
        </div>
    </div>
    {% if messages %}
    {% for message in messages %}
    <div class="row top-buffer-1">
        <div class="col-md-12">
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert alert-warning" role="alert">{{ message }}</div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success" role="alert">{{ message }}</div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {% endif %}
    <div class="row top-buffer-1">
        <div class="col-md-6 col-xs-12">
            <form method="post" action="{% url 'coursereg:instructor_update_course' course.id %}" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <label for="courseName" class="col-sm-3 control-label">Name</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="courseName" name="name" value="{{ course.title }}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="courseNum" class="col-sm-3 control-label">Number</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="courseNum" name="num" value="{{ course.num }}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="courseTerm" class="col-sm-3 control-label">Term</label>
                    <div class="col-sm-9">
                        <select id="courseTerm" name="term" class="form-control">
                            <option value="{{ course.term.id }}" selected>{{ course.term }}</option>
                            {% for term in terms %}
                            {% if term != course.term %}
                            <option value="{{ term.id }}">{{ term }}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="courseCreditSplit" class="col-sm-3 control-label">Credits</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="courseCreditSplit" name="credits" value="{{ course.credits }}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="courseCoInstructor" class="col-sm-3 control-label">Co-instructors</label>
                    <div class="col-sm-9">
                        <select id="courseCoInstructor" name="coinstructor" class="form-control" multiple="multiple">
                            {% for instructor in instructors %}
                            {% if instructor.id in coinstructor_ids %}
                            <option value="{{ instructor.id }}" selected="selected">{{ instructor.full_name }} ({{ instructor.email }})</option>
                            {% else %}
                            <option value="{{ instructor.id }}">{{ instructor.full_name }} ({{ instructor.email }})</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="courseTimings" class="col-sm-3 control-label">Class time</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="courseTimings" name="timings" value="{{ course.timings }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="courseDescription" class="col-sm-3 control-label">Description</label>
                    <div class="col-sm-9">
                        <textarea class="form-control" id="courseDescription" name="description" rows="6">{{ course.description }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <div class="checkbox">
                            <label>
                                {% if course.should_count_towards_cgpa %}
                                <input type="checkbox" name="should_count_towards_cgpa" value="true" checked>
                                {% else %}
                                <input type="checkbox" name="should_count_towards_cgpa" value="true">
                                {% endif %}
                                Course should count towards CGPA
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block head %}
{% load staticfiles %}
<link href="{% static 'coursereg/css/select2.min.css' %}" rel="stylesheet">
<link href="{% static 'coursereg/css/select2-bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'coursereg/css/typeaheadjs.css' %}" rel="stylesheet">
{% endblock %}

{% block script %}
{% load staticfiles %}
<script src="{% static 'coursereg/js/select2.min.js' %}"></script>
<script src="{% static 'coursereg/js/typeahead.bundle.min.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $("#courseCoInstructor").select2({
            placeholder: "Search for co-instructors",
            allowClear: true,
            theme: "bootstrap"
        });
        var recentCourses = [
            {% for course in recent_courses %}
            {
                "title": "{{ course.title }}",
                "num": "{{ course.num }}",
                "year": "{{ course.year }}",
                "credits": "{{ course.credits }}"
            },
            {% endfor %}
        ];

        $('#courseName').typeahead({hint: true, highlight: true, minLength: 1}, {
            name: 'title',
            source: new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.whitespace,
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                local: recentCourses.map(function(c) {
                    return c['title'];
                }).filter(function(value, index, self) {
                    return self.indexOf(value) === index;
                })
            })
        });
        $('#courseNum').typeahead({hint: true, highlight: true, minLength: 1}, {
            name: 'title',
            source: new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.whitespace,
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                local: recentCourses.map(function(c) {
                    return c['num'];
                }).filter(function(value, index, self) {
                    return self.indexOf(value) === index;
                })
            })
        });
        $('#courseCreditSplit').typeahead({hint: true, highlight: true, minLength: 1}, {
            name: 'credits',
            source: new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.whitespace,
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                local: recentCourses.map(function(c) {
                    return c['credits'];
                }).filter(function(value, index, self) {
                    return self.indexOf(value) === index;
                })
            })
        });
    });
</script>
{% endblock %}

coursereg/templates/coursereg/profile.html
{% extends "coursereg/base.html" %}

{% block body %}
{% include "coursereg/nav.html" %}
<div class="container" id="maincontainer">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1>{{ user_full_name }}</h1>
            </div>
            <p>Department: {{ request.user.department }}</p>
            {% if user_type == 'student' %}
            <p>Degree: {{ request.user.degree }}</p>
            <p>Adviser: {{ request.user.adviser.full_name }}</p>
            <p>CGPA: {{ request.user.cgpa }}</p>
            <p>Sr No: {{ request.user.sr_no }}</p>
            <p>Join date: {{ request.user.date_joined|date:'N j, Y' }}</p>
            {% endif %}
            <p>E-mail: {{ request.user.email }}</p>
            <p>Phone: {{ request.user.telephone }}</p>
        </div>
    </div>
    <div class="row top-buffer-1">
        <div class="col-md-4">
            <h3>Password</h3>
        </div>
    </div>
    <div class="row top-buffer-1">
        <div class="col-md-4">
            <form method="post" action="{% url 'coursereg:change_passwd' %}">
                {% csrf_token %}
                <input type="hidden" name="next" value="{% url 'coursereg:profile' %}">
                <div class="form-group">
                    <label for="inputPassword" class="sr-only">Current password</label>
                    <input type="password" class="form-control" id="inputPassword" name="passwd" placeholder="Current password">
                </div>
                <div class="form-group">
                    <label for="inputNewPassword" class="sr-only">New password</label>
                    <input type="password" class="form-control" id="inputNewPassword" name="newpasswd" placeholder="New password">
                </div>
                <div class="form-group">
                    <label for="inputNewPasswordAgain" class="sr-only">Verify password</label>
                    <input type="password" class="form-control" id="inputNewPasswordAgain" name="newpasswd2" placeholder="New password again">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Change Password</button>
                </div>
            </form>
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div class="row top-buffer-1">
                <div class="col-md-12">
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger" role="alert">{{ message }}</div>
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                    <div class="alert alert-warning" role="alert">{{ message }}</div>
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                    <div class="alert alert-info" role="alert">{{ message }}</div>
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="alert alert-success" role="alert">{{ message }}</div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div> <!-- /container -->
{% endblock %}